vich_uploader:
    db_driver: orm

    mappings:
        movies:
            uri_prefix: /images/movies
            upload_destination: '%kernel.project_dir%/public/images/movies'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
